### ISSUE TITLE
Unauthorized Error when executed in same execution as EKS cluster creation

### ISSUE THREAD

**Issue by tcd156** [aidanmelen/terraform-aws-eks-auth#10]
**Describe the Bug**

Thanks so much for this project! I've been following your git comments on the EKS terraform module repo and really appreciate you pulling this out.

Currently, I am unable to perform this operation in the same terraform execution where the EKS cluster is created. Are you expecting this module to only perform updates to already existing clusters, or do I just have a bug? Hashicorp notes here that interpolation can cause issues:
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources

**Expected Behavior**

1. create an EKS cluster
2. Use this module to modify config map
3. cluster works with config map changes

**Actual Behavior**

1. EKS cluster is created
2. this module begins to execute
3. Receive "Unauthorized!" error
4. Run again, and execution succeeds

**Steps to Reproduce the Problem**
I'm using a setup that is identical to the examples here.

**Comment by tcd156** [comment]
I fat fingered the aws eks module version number so it was totally my fault :)

**Comment by aidanmelen** [comment]
> Are you expecting this module to only perform updates to already existing clusters, or do I just have a bug?

I wrote tests for this module with Terratest. This will `init`, `apply`, assert outputs, and `destroy` the terraform. I run these tests against the [complete](https://github.com/aidanmelen/terraform-aws-eks-auth/tree/main/examples/complete) and [patch](https://github.com/aidanmelen/terraform-aws-eks-auth/tree/main/examples/patch) examples which are setup to create the EKS module and EKS Auth module in the same run.

I expect that this module should work from nothing or from a pre-existing cluster.

**Comment by aidanmelen** [comment]
> I fat fingered the aws eks module version number so it was totally my fault :)

happens to the best of us 😆
