### ISSUE TITLE
How to use module with kubernetes provider alias?

### ISSUE THREAD

**Issue by SelfhostedPro** [aidanmelen/terraform-aws-eks-auth#11]
**Describe the Bug**

When applying with what I think is the correct configuration:
```tf
module "sandbox_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.11.0"
  cluster_name    = "sandbox"
  cluster_version = "1.21"

  vpc_id = module.development_vpc.vpc_id

  eks_managed_node_groups = {
    sandbox = {
      min_size     = 1
      max_size     = 5
      desired_size = 1

      security_group_name = "sandbox_worker_sg"

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
      labels = {
        Environment = "development"
      }
      taints = {
      }
    }
  }
}

data "aws_eks_cluster" "sandbox_cluster" {
  name = module.sandbox_cluster.cluster_id
}

data "aws_eks_cluster_auth" "sandbox_cluster_auth" {
  name = module.sandbox_cluster.cluster_id
}

provider "kubernetes" {
  alias                  = "sandbox_kubernetes"
  host                   = data.aws_eks_cluster.sandbox_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.sandbox_cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.sandbox_cluster_auth.token
}

module "eks_auth" {
  source = "aidanmelen/eks-auth/aws"
  eks    = module.sandbox_cluster

  map_roles = [
    {
      rolearn  = var.kubectl_access_role_arn
      username = "kubernetes_master"
      groups   = ["system:masters"]
    }
  ]
}
```

Returns the following error:
```
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/serviceaccounts": dial tcp [::1]:80: connect: connection refused
│ 
│   with module.development.module.eks_auth.kubernetes_service_account_v1.aws_auth_init,
│   on .terraform/modules/development.eks_auth/main.tf line 47, in resource "kubernetes_service_account_v1" "aws_auth_init":
│   47: resource "kubernetes_service_account_v1" "aws_auth_init" {
│ 
```
**Expected Behavior**

For the aws_auth configmap to change

**Actual Behavior**

Fails at this point. Tried adding configuration for the kubernetes provider. I did add that in in an attempt to get this working so it's possible there's something in state that's preventing this from working or something to do with networking as it's not giving an actual IP that it's trying to connect to.

**Steps to Reproduce the Problem**
  1. Setup a .tf file with the above tf code
  2. run terraform init and terraform apply.
  
You'll need to create a variable for the arn that you're trying to add into the configmap.

**Comment by aidanmelen** [comment]
I suspect that this has something to with the alias you set on the kuberenetes provider. Try calling the `eks_auth` module and pass the provider alias.

Please see the official [docs](https://www.terraform.io/language/providers/configuration#selecting-alternate-provider-configurations) for passing provider aliases to modules.

**Comment by aidanmelen** [comment]
i think you need this

```hcl
module "eks_auth" {
  source = "aidanmelen/eks-auth/aws"

  providers = {
    kubernetes = kubernetes.sandbox_kubernetes
  }

  eks = module.sandbox_cluster

  map_roles = [
    {
      rolearn  = var.kubectl_access_role_arn
      username = "kubernetes_master"
      groups   = ["system:masters"]
    }
  ]
}
```

**Comment by aidanmelen** [comment]
I modified the basic example to use a kubernetes provider alias and it was successful with my suggestion above. Here are the logs from the run:

**Comment by aidanmelen** [comment]
I modified the basic example to use a kubernetes provider alias and passed the provider alias to the module. It was successful. Please follow this suggestion above.

Here are the logs from that successful test: [k8s_provider_alias.log](https://github.com/aidanmelen/terraform-aws-eks-auth/files/8329011/k8s_provider_alias.log)

**Comment by SelfhostedPro** [comment]
That did it! Thanks! Didn't realize I could pass inside the module there.
