### ISSUE TITLE
Does not update the aws-auth for newly created cluster.

### ISSUE THREAD

**Issue by skaur23-ops** [aidanmelen/terraform-aws-eks-auth#16]
I am trying to create a new EKS using terraform-eks official module, and to ease the pain of creating new aws-auth configmap I was trying to use this module. But since I have multiple clusters in my kube-config, this module updates the configmap of my current-context and not the newly created EKS. Is this the expected behavior?

**Comment by aidanmelen** [comment]
I would like to clarify that the `aws-auth` configmap declares which IAM resources can authenticate to the EKS cluster. On the other hand, the local `~/.kube/config` describes which IAM credentials to use with the k8s client. Assuming your `aws-auth` grants your IAM user/role corrently, then you can use the AWS CLL to update your kube config:

```console
$ aws eks update-kubeconfig --name ex-basic --profile my-aws-credentials-file-profile
```

**Comment by skaur23-ops** [comment]
I understand, but that's not the issue. Let me explain. I am creating a new EKS and I have an eks-auth.tf which basically uses this module to add a new IAM role to the configmap. When I do the terraform apply, the cluster creation happens as usual, but it updates the aws-auth configmap(with additional settings using this module) of the current-context on my machine which is " not " this cluster. 
If I remove the kube-config from my machine and try to create the cluster from scratch, it gives me the following error with this module :
```
kube-system/aws-auth failed to create kubernetes rest client for update of resource Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
```

So, do I need to first create the cluster, add it to my kube-config and switch to that context and then do the terraform apply for this module?

**Comment by aidanmelen** [comment]
let me break down the order of operations:

1. Pass aws credentials to [aws provider.](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/providers.tf#L1-L10)
2. [The `eks` module creates the EKS cluster ](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/main.tf#L5-L16).
3. A [`aws_eks_cluster_auth`](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/data.tf#L5-L7) data resource retrieves STS credentials for the EKS cluster.
4. [Pass the STS credentials to the kubernetes provider.](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/providers.tf#L12-L16)
5. The [eks-auth module](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/main.tf#L18-L21) will use the kubernetes provider to configure the `aws-auth` configmap on the cluster.
6. run `aws eks update-kubeconfig ...` locally to update your local `~/.kube/config` to connect to the kubernetes cluster endpoint. 

This is demonstrated in the [basic example](https://github.com/aidanmelen/terraform-aws-eks-auth/tree/main/examples/basic). This order of operations is not unique to this module. The same can be seen in the [v17.X.X eks module examples](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v17.24.0/examples/complete/main.tf). you can verify order in which these events occur in the [test.logs](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/test/terraform_basic_test.log).

**Comment by skaur23-ops** [comment]
This is exactly what I am doing. But it would still update the configmap of a cluster existing on my machine and not the one I am trying to create and update the changes for.

**Comment by aidanmelen** [comment]
If creating multiple eks cluster in the same terraform run, then you will need to use provider aliases. Please see this [closed issue](https://github.com/aidanmelen/terraform-aws-eks-auth/issues/11) for more information.

**Comment by aidanmelen** [comment]
If that doesn't fix you issue then you will need to share your terraform because I am not able to reproduce.

**Comment by aidanmelen** [comment]
> This is exactly what I am doing. But it would still update the configmap of a cluster existing on my machine and not the one I am trying to create and update the changes for.

ahh i think I know the issue. The example is indeed broken. Since the kubernetes provider does not currently have patch functionality (that is soon to change with https://github.com/hashicorp/terraform-provider-kubernetes/pull/1671#issuecomment-1086183819), the current version of this module uses the [kubectl provider](https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/versions.tf#L10-L14). This provider takes the exact same arguments as the kubernetes provider. For example:

```hcl
provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

I will fix the examples, thanks for bringing this to my attention!

**Comment by aidanmelen** [comment]
the example is fixed: https://github.com/aidanmelen/terraform-aws-eks-auth/blob/main/examples/basic/providers.tf

**Comment by skaur23-ops** [comment]
Thank you! It seems to work now after adding the kubectl provider.
