### ISSUE TITLE
Possibility of keeping this alive ?

### ISSUE THREAD

**Issue by pmbeaumier** [aidanmelen/terraform-aws-eks-auth#21]
While version 'v18.20.0' of the [terraform eks module](https://github.com/terraform-aws-modules/terraform-aws-eks) brings back the management of the `aws-auth` configmap, it makes use of a `local-exec` to retrieve the auth token for the internal kubernetes provider and this addition prevents its use on Terraform Cloud.
I was wondering if you'd be willing to keep this project alive as it  definitely helps folks who can't use the new EKS module feature.
Thanks

**Comment by aidanmelen** [comment]
Sorry, I should clarify the deprecation notice. This module will remain on terraform registry. I won't be taking it down. Feel free to keep using it.

This module is redundant now that the EKS module supports aws-auth management again. For this reason, I was merely going to archive this GitHub repo to prevent new features request and to promote the use of the EKS module in the future.

**Comment by aidanmelen** [comment]
> it makes use of a local-exec to retrieve the auth token

I don't think this is true. The latest version of the EKS module manages the aws-auth configmap with the config_map_v1_data resource, which shares the same implementation of this module, version 1.0.0. The Kubernetes provider resource is not dependent on local-exec like prior versions of the EKS module.

**Comment by aidanmelen** [comment]
This code snippet should help

```hcl
provider "aws" {
  region = var.aws_region
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.20.2"

  cluster_name = local.name
  vpc_id       = module.vpc.vpc_id
  subnet_ids   = module.vpc.private_subnets

  # aws-auth configmap
  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::66666666666:role/role1"
      username = "role1"
      groups   = ["system:masters"]
    },
  ]

  aws_auth_users = [
    {
      userarn  = "arn:aws:iam::66666666666:user/user1"
      username = "user1"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::66666666666:user/user2"
      username = "user2"
      groups   = ["system:masters"]
    },
  ]

  aws_auth_accounts = [
    "777777777777",
    "888888888888",
  ]
}
```

**Comment by pmbeaumier** [comment]
You're totally right, my bad, I was looking at examples and thought they had included the definition of the kubernetes provider inside the module and were therefore forcing the use of the `local-exec`. Thanks for the response and clarification.

**Comment by aidanmelen** [comment]
> You're totally right, my bad, I was looking at examples and thought they had included the definition of the kubernetes provider inside the module and were therefore forcing the use of the `local-exec`. Thanks for the response and clarification.

I am really glad I could help. Thanks for the question!
