### ISSUE TITLE
bug: `data.aws_eks_cluster_auth.cluster.token` expires before completion

### ISSUE THREAD

**Issue by aidanmelen** [aidanmelen/terraform-aws-eks-auth#9]
**Describe the Bug**

The `data.aws_eks_cluster_auth.cluster.token` can expire causing the kubernetes provider to timeout and fail.

<img width="1239" alt="Screen Shot 2022-03-21 at 9 46 35 PM" src="https://user-images.githubusercontent.com/7491003/159403964-04cdab48-43f1-4fee-97fc-f384faa7856a.png">

**Expected Behavior**

The kubenetes job always runs to completion before the `data.aws_eks_cluster_auth.cluster.token` expires.

**Actual Behavior**

sometimes the token expires and the terraform apply fails.

**Steps to Reproduce the Problem**
  1. run the complete example.
  2. most of the time it runs to completion before the token timeout.
  3. but sometimes it doesn't and the apply will fail.

**Comment by aidanmelen** [comment]
This is scenario B from this hashicorp blog: https://support.hashicorp.com/hc/en-us/articles/4408936406803-Kubernetes-Provider-block-fails-with-connect-connection-refused-

I am closing because this is an issue with the data resource/underlying API. Users should be able to extend the token timeout.

**Comment by aidanmelen** [comment]
solution is to run another apply which will get a new token. The second apply should succeed because the cluster should already be created and we have a new token

**Comment by aidanmelen** [comment]
The timeout is 15 minutes... I found the [upstream issue](https://github.com/hashicorp/terraform-provider-aws/blob/8f7a597d0c2408e5d282b17982116c4cc777d83d/internal/service/eks/token.go#L177-L197) in the aws provider and the issue for the [aws golang lib](https://github.com/aws/aws-sdk-go/issues/2167).

**Comment by StewartThomson** [comment]
Adding

```
provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate =  module.eks.cluster_certificate_authority_data
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

to my module resolved this for me
